import { Geist, Geist_Mono, Josefin_Sans, Lato } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/redux/provider";
import { AuthInitializer } from "@/redux/AuthInitializer";
import AuthGuard from "@/hooks/authGuard";
import useNotificationsSocket from "@/lib/useNotificationsSocket";

const lato = Lato({
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"], // choose what you need
  variable: "--font-lato", // makes it usable in Tailwind
});

const josefin = Josefin_Sans({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"], // optional
  variable: "--font-josefin", // makes it usable in Tailwind
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Car Auction App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${josefin.variable} ${geistMono.variable} ${lato.variable} antialiased`}
      >
        <ReduxProvider>
          <AuthInitializer />
          <AuthGuard>
            {children}
          </AuthGuard>
        </ReduxProvider>
      </body>
    </html>
  );
}
